name: publish
on:
  push:
    branches:
      - main
    tags:        
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          node-version: latest
          registry-url: https://registry.npmjs.org/
      - name: cloudflare workers publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          apiToken: ${{ secrets.CF_API_TOKEN }}
          secrets: |
            SECRET_TELEGRAM_API_TOKEN
        env:
          SECRET_TELEGRAM_API_TOKEN: ${{ secrets.SECRET_TELEGRAM_API_TOKEN }}
